
name: bharathlink_full_demo
description: A full working BharathLink demo with mock login.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.32.0  # Add this line
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.3
  image_picker: ^1.1.2
  firebase_storage: ^11.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/