// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARUMgZkX2bFnIUN0bg-KGj920MPCzvmPY',
    appId: '1:724794500028:web:ac74c945c6ad96c97781b9',
    messagingSenderId: '724794500028',
    projectId: 'bharathlink-app',
    authDomain: 'bharathlink-app.firebaseapp.com',
    storageBucket: 'bharathlink-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1K2XDMXCgFxHPc0oRCyZH4W8ftV9abXs',
    appId: '1:724794500028:android:96f6edd2ab3170b37781b9',
    messagingSenderId: '724794500028',
    projectId: 'bharathlink-app',
    storageBucket: 'bharathlink-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhRk-rbzUlGZDnzuQfulPtOFt-xpL8pPo',
    appId: '1:724794500028:ios:1c60903509ad0e857781b9',
    messagingSenderId: '724794500028',
    projectId: 'bharathlink-app',
    storageBucket: 'bharathlink-app.firebasestorage.app',
    iosBundleId: 'com.example.bharathlinkFullDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhRk-rbzUlGZDnzuQfulPtOFt-xpL8pPo',
    appId: '1:724794500028:ios:1c60903509ad0e857781b9',
    messagingSenderId: '724794500028',
    projectId: 'bharathlink-app',
    storageBucket: 'bharathlink-app.firebasestorage.app',
    iosBundleId: 'com.example.bharathlinkFullDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARUMgZkX2bFnIUN0bg-KGj920MPCzvmPY',
    appId: '1:724794500028:web:ce0c932c509d42767781b9',
    messagingSenderId: '724794500028',
    projectId: 'bharathlink-app',
    authDomain: 'bharathlink-app.firebaseapp.com',
    storageBucket: 'bharathlink-app.firebasestorage.app',
  );
}
